package retailstore;
// Generated Nov 1, 2015 11:23:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int id;
     private String name;
     private Date createdAt;
     private Set productses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int id) {
        this.id = id;
    }
    public Categories(int id, String name, Date createdAt, Set productses) {
       this.id = id;
       this.name = name;
       this.createdAt = createdAt;
       this.productses = productses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }
}
