package retailstore;
// Generated Oct 31, 2015 10:17:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int id;
     private Categories categories;
     private String name;
     private String barcode;
     private Date createdAt;
     private Set purchaseItemses = new HashSet(0);

    public Products() {
    }

	
    public Products(int id, String name, String barcode) {
        this.id = id;
        this.name = name;
        this.barcode = barcode;
    }
    public Products(int id, Categories categories, String name, String barcode, Date createdAt, Set purchaseItemses) {
       this.id = id;
       this.categories = categories;
       this.name = name;
       this.barcode = barcode;
       this.createdAt = createdAt;
       this.purchaseItemses = purchaseItemses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getPurchaseItemses() {
        return this.purchaseItemses;
    }
    
    public void setPurchaseItemses(Set purchaseItemses) {
        this.purchaseItemses = purchaseItemses;
    }




}


