package retailstore;
// Generated Nov 1, 2015 11:23:18 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PurchaseItems generated by hbm2java
 */
public class PurchaseItems  implements java.io.Serializable {


     private int id;
     private Products products;
     private Purchases purchases;
     private int quantity;
     private Date createdAt;

    public PurchaseItems() {
    }

	
    public PurchaseItems(int id, Products products, Purchases purchases, int quantity) {
        this.id = id;
        this.products = products;
        this.purchases = purchases;
        this.quantity = quantity;
    }
    public PurchaseItems(int id, Products products, Purchases purchases, int quantity, Date createdAt) {
       this.id = id;
       this.products = products;
       this.purchases = purchases;
       this.quantity = quantity;
       this.createdAt = createdAt;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Purchases getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Purchases purchases) {
        this.purchases = purchases;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


