package retailstore;
// Generated Oct 31, 2015 10:17:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private Boolean admin;
     private Date createdAt;

    public Users() {
    }

	
    public Users(int id) {
        this.id = id;
    }
    public Users(int id, String username, String password, Boolean admin, Date createdAt) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.admin = admin;
       this.createdAt = createdAt;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


